# Cloudflare Pages / D1 Configuration for Paldo
name = "paldo-dog"
pages_build_output_dir = ".open-next/assets"
compatibility_date = "2026-06-21"
compatibility_flags = [ "nodejs_compat", "global_fetch_strictly_public" ]

[[d1_databases]]
binding = "DB"
database_name = "DB"
database_id = "049c3da8-77fa-45f4-8d18-8c22d2a73a53"

[[r2_buckets]]
binding = "R2"
bucket_name = "paldo-r2"
